spring.application.name=inventory-manager-api

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_manager
spring.datasource.username=postgres
spring.datasource.password=PASSWORD

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect